# Generated by CMake 2.8.2

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target hdf5
ADD_LIBRARY(hdf5 STATIC IMPORTED)

# Create imported target hdf5_tools
ADD_LIBRARY(hdf5_tools STATIC IMPORTED)

# Create imported target hdf5_f90cstub
ADD_LIBRARY(hdf5_f90cstub STATIC IMPORTED)

# Create imported target hdf5_fortran
ADD_LIBRARY(hdf5_fortran STATIC IMPORTED)

# Create imported target hdf5_hl_f90cstub
ADD_LIBRARY(hdf5_hl_f90cstub STATIC IMPORTED)

# Create imported target hdf5_hl_fortran
ADD_LIBRARY(hdf5_hl_fortran STATIC IMPORTED)

# Create imported target hdf5_cpp
ADD_LIBRARY(hdf5_cpp STATIC IMPORTED)

# Create imported target hdf5_hl
ADD_LIBRARY(hdf5_hl STATIC IMPORTED)

# Create imported target hdf5_hl_cpp
ADD_LIBRARY(hdf5_hl_cpp STATIC IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/hdf5-targets-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
