#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Compute the installation prefix relative to this file.
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Import target "hdf5" for configuration "Release"
SET_PROPERTY(TARGET hdf5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hdf5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ws2_32;wsock32;C:/extlibs/zlib/lib/zlib.lib;c:/extlibs/szip/enc/lib/libszip.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/hdf5.lib"
  )

# Import target "hdf5_tools" for configuration "Release"
SET_PROPERTY(TARGET hdf5_tools APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hdf5_tools PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/tools/hdf5_tools.lib"
  )

# Import target "hdf5_f90cstub" for configuration "Release"
SET_PROPERTY(TARGET hdf5_f90cstub APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hdf5_f90cstub PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/hdf5_f90cstub.lib"
  )

# Import target "hdf5_fortran" for configuration "Release"
SET_PROPERTY(TARGET hdf5_fortran APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hdf5_fortran PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "Fortran"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5_f90cstub;hdf5"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/hdf5_fortran.lib"
  )

# Import target "hdf5_hl_f90cstub" for configuration "Release"
SET_PROPERTY(TARGET hdf5_hl_f90cstub APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hdf5_hl_f90cstub PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5_f90cstub;hdf5_hl"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/hdf5_hl_f90cstub.lib"
  )

# Import target "hdf5_hl_fortran" for configuration "Release"
SET_PROPERTY(TARGET hdf5_hl_fortran APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hdf5_hl_fortran PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "Fortran"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5_hl_f90cstub;hdf5_fortran"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/hdf5_hl_fortran.lib"
  )

# Import target "hdf5_cpp" for configuration "Release"
SET_PROPERTY(TARGET hdf5_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hdf5_cpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/hdf5_cpp.lib"
  )

# Import target "hdf5_hl" for configuration "Release"
SET_PROPERTY(TARGET hdf5_hl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hdf5_hl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/hdf5_hl.lib"
  )

# Import target "hdf5_hl_cpp" for configuration "Release"
SET_PROPERTY(TARGET hdf5_hl_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(hdf5_hl_cpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5_hl;hdf5"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/hdf5_hl_cpp.lib"
  )

# Cleanup temporary variables.
SET(_IMPORT_PREFIX)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
