#!/bin/bash
cd /src

# Defina o caminho da pasta onde estão os arquivos .f90
SRCPATH="/src/SmallTools/Numerical_recipes_f90"

# Entre no diretório
cd $SRCPATH

# Remova arquivos objeto antigos e a biblioteca, se existirem
rm -f *.o libnr.a

ifort -c -O0 -g -real-size 32 -o  ran.o ran.f90
ifort -c -O0 -g -real-size 32 -o  nrtype.o nrtype.f90
ifort -c -O0 -g -real-size 32 -o  nr.o nr.f90
ifort -c -O0 -g -real-size 32 -o  hypgeo.o hypgeo.f90
ifort -c -O0 -g -real-size 32 -o  kermom.o kermom.f90
ifort -c -O0 -g -real-size 32 -o  mpops.o mpops.f90
ifort -c -O0 -g -real-size 32 -o  nrutil.o nrutil.f90
ifort -c -O0 -g -real-size 32 -o  sphfpt.o sphfpt.f90
ifort -c -O0 -g -real-size 32 -o  rkdumb.o rkdumb.f90
ifort -c -O0 -g -real-size 32 -o  quad3d.o quad3d.f90
ifort -c -O0 -g -real-size 32 -o  hufmak.o hufmak.f90
ifort -c -O0 -g -real-size 32 -o  dlinmin.o dlinmin.f90
ifort -c -O0 -g -real-size 32 -o  arcmak.o arcmak.f90
ifort -c -O0 -g -real-size 32 -o  linmin.o linmin.f90
ifort -c -O0 -g -real-size 32 -o  xlinbcg_data.o xlinbcg_data.f90
ifort -c -O0 -g -real-size 32 -o  sfroid.o sfroid.f90
ifort -c -O0 -g -real-size 32 -o  sphoot.o sphoot.f90
ifort -c -O0 -g -real-size 32 -o  pwtset.o pwtset.f90
ifort -c -O0 -g -real-size 32 -o  ran_stat.o ran_stat.f90
ifort -c -O0 -g -real-size 32 -o  odeint.o odeint.f90
ifort -c -O0 -g -real-size 32 -o  fmin.o fmin.f90
ifort -c -O0 -g -real-size 32 -o  chixy.o chixy.f90
ifort -c -O0 -g -real-size 32 -o  stoerm.o stoerm.f90
ifort -c -O0 -g -real-size 32 -o  spear.o spear.f90
ifort -c -O0 -g -real-size 32 -o  scrsho.o scrsho.f90
ifort -c -O0 -g -real-size 32 -o  rtnewt.o rtnewt.f90
ifort -c -O0 -g -real-size 32 -o  ran1.o ran1.f90
ifort -c -O0 -g -real-size 32 -o  pearsn.o pearsn.f90
ifort -c -O0 -g -real-size 32 -o  mpinv.o mpinv.f90
ifort -c -O0 -g -real-size 32 -o  moment.o moment.f90
ifort -c -O0 -g -real-size 32 -o  midsqu.o midsqu.f90
ifort -c -O0 -g -real-size 32 -o  machar.o machar.f90
ifort -c -O0 -g -real-size 32 -o  ludcmp.o ludcmp.f90
ifort -c -O0 -g -real-size 32 -o  gammln.o gammln.f90
ifort -c -O0 -g -real-size 32 -o  frprmn.o frprmn.f90
ifort -c -O0 -g -real-size 32 -o  fredin.o fredin.f90
ifort -c -O0 -g -real-size 32 -o  fitexy.o fitexy.f90
ifort -c -O0 -g -real-size 32 -o  fgauss.o fgauss.f90
ifort -c -O0 -g -real-size 32 -o  cyclic.o cyclic.f90
ifort -c -O0 -g -real-size 32 -o  cntab2.o cntab2.f90
ifort -c -O0 -g -real-size 32 -o  bessi0.o bessi0.f90
ifort -c -O0 -g -real-size 32 -o  wwghts.o wwghts.f90
ifort -c -O0 -g -real-size 32 -o  svbksb.o svbksb.f90
ifort -c -O0 -g -real-size 32 -o  stiff.o stiff.f90
ifort -c -O0 -g -real-size 32 -o  shoot.o shoot.f90
ifort -c -O0 -g -real-size 32 -o  rj.o rj.f90
ifort -c -O0 -g -real-size 32 -o  rf.o rf.f90
ifort -c -O0 -g -real-size 32 -o  qrupdt.o qrupdt.f90
ifort -c -O0 -g -real-size 32 -o  polin2.o polin2.f90
ifort -c -O0 -g -real-size 32 -o  julday.o julday.f90
ifort -c -O0 -g -real-size 32 -o  index_by.o index_by.f90
ifort -c -O0 -g -real-size 32 -o  gaulag.o gaulag.f90
ifort -c -O0 -g -real-size 32 -o  gammq.o gammq.f90
ifort -c -O0 -g -real-size 32 -o  fleg.o fleg.f90
ifort -c -O0 -g -real-size 32 -o  fit.o fit.f90
ifort -c -O0 -g -real-size 32 -o  cosft1.o cosft1.f90
ifort -c -O0 -g -real-size 32 -o  beta.o beta.f90
ifort -c -O0 -g -real-size 32 -o  bessjy.o bessjy.f90
ifort -c -O0 -g -real-size 32 -o  beschb.o beschb.f90
ifort -c -O0 -g -real-size 32 -o  amebsa.o amebsa.f90
ifort -c -O0 -g -real-size 32 -o  wt1.o wt1.f90
ifort -c -O0 -g -real-size 32 -o  sprsax.o sprsax.f90
ifort -c -O0 -g -real-size 32 -o  splint.o splint.f90
ifort -c -O0 -g -real-size 32 -o  rtbis.o rtbis.f90
ifort -c -O0 -g -real-size 32 -o  rlft3.o rlft3.f90
ifort -c -O0 -g -real-size 32 -o  rd.o rd.f90
ifort -c -O0 -g -real-size 32 -o  pzextr.o pzextr.f90
ifort -c -O0 -g -real-size 32 -o  midpnt.o midpnt.f90
ifort -c -O0 -g -real-size 32 -o  laguer.o laguer.f90
ifort -c -O0 -g -real-size 32 -o  gaujac.o gaujac.f90
ifort -c -O0 -g -real-size 32 -o  fourcol_.o fourcol_.f90
ifort -c -O0 -g -real-size 32 -o  flmoon.o flmoon.f90
ifort -c -O0 -g -real-size 32 -o  eigsrt.o eigsrt.f90
ifort -c -O0 -g -real-size 32 -o  cosft2.o cosft2.f90
ifort -c -O0 -g -real-size 32 -o  betai.o betai.f90
ifort -c -O0 -g -real-size 32 -o  bessy0.o bessy0.f90
ifort -c -O0 -g -real-size 32 -o  bessi1.o bessi1.f90
ifort -c -O0 -g -real-size 32 -o  sprsdiag.o sprsdiag.f90
ifort -c -O0 -g -real-size 32 -o  splie2.o splie2.f90
ifort -c -O0 -g -real-size 32 -o  sobseq.o sobseq.f90
ifort -c -O0 -g -real-size 32 -o  select.o select.f90
ifort -c -O0 -g -real-size 32 -o  rtflsp.o rtflsp.f90
ifort -c -O0 -g -real-size 32 -o  poldiv.o poldiv.f90
ifort -c -O0 -g -real-size 32 -o  newt.o newt.f90
ifort -c -O0 -g -real-size 32 -o  medfit.o medfit.f90
ifort -c -O0 -g -real-size 32 -o  interp.o interp.f90
ifort -c -O0 -g -real-size 32 -o  hypdrv.o hypdrv.f90
ifort -c -O0 -g -real-size 32 -o  gamdev.o gamdev.f90
ifort -c -O0 -g -real-size 32 -o  eulsum.o eulsum.f90
ifort -c -O0 -g -real-size 32 -o  chebev.o chebev.f90
ifort -c -O0 -g -real-size 32 -o  chder.o chder.f90
ifort -c -O0 -g -real-size 32 -o  bandec.o bandec.f90
ifort -c -O0 -g -real-size 32 -o  arcode.o arcode.f90
ifort -c -O0 -g -real-size 32 -o  tridag.o tridag.f90
ifort -c -O0 -g -real-size 32 -o  tptest.o tptest.f90
ifort -c -O0 -g -real-size 32 -o  sphbes.o sphbes.f90
ifort -c -O0 -g -real-size 32 -o  sor.o sor.f90
ifort -c -O0 -g -real-size 32 -o  shootf.o shootf.f90
ifort -c -O0 -g -real-size 32 -o  select_i.o select_i.f90
ifort -c -O0 -g -real-size 32 -o  linbcg.o linbcg.f90
ifort -c -O0 -g -real-size 32 -o  indexx.o indexx.f90
ifort -c -O0 -g -real-size 32 -o  four2.o four2.f90
ifort -c -O0 -g -real-size 32 -o  evlmem.o evlmem.f90
ifort -c -O0 -g -real-size 32 -o  dftint.o dftint.f90
ifort -c -O0 -g -real-size 32 -o  bessj.o bessj.f90
ifort -c -O0 -g -real-size 32 -o  banmul.o banmul.f90
ifort -c -O0 -g -real-size 32 -o  vander.o vander.f90
ifort -c -O0 -g -real-size 32 -o  ttest.o ttest.f90
ifort -c -O0 -g -real-size 32 -o  tred2.o tred2.f90
ifort -c -O0 -g -real-size 32 -o  sort3.o sort3.f90
ifort -c -O0 -g -real-size 32 -o  select_h.o select_h.f90
ifort -c -O0 -g -real-size 32 -o  rstrct.o rstrct.f90
ifort -c -O0 -g -real-size 32 -o  rotate.o rotate.f90
ifort -c -O0 -g -real-size 32 -o  resid.o resid.f90
ifort -c -O0 -g -real-size 32 -o  probks.o probks.f90
ifort -c -O0 -g -real-size 32 -o  period.o period.f90
ifort -c -O0 -g -real-size 32 -o  memcof.o memcof.f90
ifort -c -O0 -g -real-size 32 -o  gasdev.o gasdev.f90
ifort -c -O0 -g -real-size 32 -o  fourrow.o fourrow.f90
ifort -c -O0 -g -real-size 32 -o  four1_ga.o four1_ga.f90
ifort -c -O0 -g -real-size 32 -o  dftcor.o dftcor.f90
ifort -c -O0 -g -real-size 32 -o  bessk1.o bessk1.f90
ifort -c -O0 -g -real-size 32 -o  bessk.o bessk.f90
ifort -c -O0 -g -real-size 32 -o  asolve.o asolve.f90
ifort -c -O0 -g -real-size 32 -o  toeplz.o toeplz.f90
ifort -c -O0 -g -real-size 32 -o  sprsin.o sprsin.f90
ifort -c -O0 -g -real-size 32 -o  spline.o spline.f90
ifort -c -O0 -g -real-size 32 -o  splin2.o splin2.f90
ifort -c -O0 -g -real-size 32 -o  sort_she.o sort_she.f90
ifort -c -O0 -g -real-size 32 -o  simplx.o simplx.f90
ifort -c -O0 -g -real-size 32 -o  rlft2.o rlft2.f90
ifort -c -O0 -g -real-size 32 -o  relax2.o relax2.f90
ifort -c -O0 -g -real-size 32 -o  ran3.o ran3.f90
ifort -c -O0 -g -real-size 32 -o  qromo.o qromo.f90
ifort -c -O0 -g -real-size 32 -o  mppi.o mppi.f90
ifort -c -O0 -g -real-size 32 -o  midinf.o midinf.f90
ifort -c -O0 -g -real-size 32 -o  ks2d2s.o ks2d2s.f90
ifort -c -O0 -g -real-size 32 -o  hqr.o hqr.f90
ifort -c -O0 -g -real-size 32 -o  fpoly.o fpoly.f90
ifort -c -O0 -g -real-size 32 -o  expdev.o expdev.f90
ifort -c -O0 -g -real-size 32 -o  ellf.o ellf.f90
ifort -c -O0 -g -real-size 32 -o  dbrent.o dbrent.f90
ifort -c -O0 -g -real-size 32 -o  correl.o correl.f90
ifort -c -O0 -g -real-size 32 -o  broydn.o broydn.f90
ifort -c -O0 -g -real-size 32 -o  amoeba.o amoeba.f90
ifort -c -O0 -g -real-size 32 -o  zbrent.o zbrent.f90
ifort -c -O0 -g -real-size 32 -o  trapzd.o trapzd.f90
ifort -c -O0 -g -real-size 32 -o  spctrm.o spctrm.f90
ifort -c -O0 -g -real-size 32 -o  sort.o sort.f90
ifort -c -O0 -g -real-size 32 -o  slvsml.o slvsml.f90
ifort -c -O0 -g -real-size 32 -o  simpr.o simpr.f90
ifort -c -O0 -g -real-size 32 -o  ran0.o ran0.f90
ifort -c -O0 -g -real-size 32 -o  polcoe.o polcoe.f90
ifort -c -O0 -g -real-size 32 -o  pcshft.o pcshft.f90
ifort -c -O0 -g -real-size 32 -o  mmid.o mmid.f90
ifort -c -O0 -g -real-size 32 -o  mgfas.o mgfas.f90
ifort -c -O0 -g -real-size 32 -o  ksone.o ksone.f90
ifort -c -O0 -g -real-size 32 -o  hunt.o hunt.f90
ifort -c -O0 -g -real-size 32 -o  gaussj.o gaussj.f90
ifort -c -O0 -g -real-size 32 -o  fourn_ga.o fourn_ga.f90
ifort -c -O0 -g -real-size 32 -o  fasper.o fasper.f90
ifort -c -O0 -g -real-size 32 -o  erfc.o erfc.f90
ifort -c -O0 -g -real-size 32 -o  elmhes.o elmhes.f90
ifort -c -O0 -g -real-size 32 -o  chstwo.o chstwo.f90
ifort -c -O0 -g -real-size 32 -o  caldat.o caldat.f90
ifort -c -O0 -g -real-size 32 -o  banbks.o banbks.f90
ifort -c -O0 -g -real-size 32 -o  zbrak.o zbrak.f90
ifort -c -O0 -g -real-size 32 -o  wtn.o wtn.f90
ifort -c -O0 -g -real-size 32 -o  tqli.o tqli.f90
ifort -c -O0 -g -real-size 32 -o  sort_rad.o sort_rad.f90
ifort -c -O0 -g -real-size 32 -o  select_b.o select_b.f90
ifort -c -O0 -g -real-size 32 -o  rtsafe.o rtsafe.f90
ifort -c -O0 -g -real-size 32 -o  rkck.o rkck.f90
ifort -c -O0 -g -real-size 32 -o  quadvl.o quadvl.f90
ifort -c -O0 -g -real-size 32 -o  pythag.o pythag.f90
ifort -c -O0 -g -real-size 32 -o  mpsqrt.o mpsqrt.f90
ifort -c -O0 -g -real-size 32 -o  midsql.o midsql.f90
ifort -c -O0 -g -real-size 32 -o  lubksb.o lubksb.f90
ifort -c -O0 -g -real-size 32 -o  kstwo.o kstwo.f90
ifort -c -O0 -g -real-size 32 -o  gser.o gser.f90
ifort -c -O0 -g -real-size 32 -o  gaucof.o gaucof.f90
ifort -c -O0 -g -real-size 32 -o  ftest.o ftest.f90
ifort -c -O0 -g -real-size 32 -o  fdjac.o fdjac.f90
ifort -c -O0 -g -real-size 32 -o  factln.o factln.f90
ifort -c -O0 -g -real-size 32 -o  cntab1.o cntab1.f90
ifort -c -O0 -g -real-size 32 -o  chsone.o chsone.f90
ifort -c -O0 -g -real-size 32 -o  bessi.o bessi.f90
ifort -c -O0 -g -real-size 32 -o  airy.o airy.f90
ifort -c -O0 -g -real-size 32 -o  voltra.o voltra.f90
ifort -c -O0 -g -real-size 32 -o  stifbs.o stifbs.f90
ifort -c -O0 -g -real-size 32 -o  sprstp.o sprstp.f90
ifort -c -O0 -g -real-size 32 -o  relax.o relax.f90
ifort -c -O0 -g -real-size 32 -o  recur1.o recur1.f90
ifort -c -O0 -g -real-size 32 -o  ratint.o ratint.f90
ifort -c -O0 -g -real-size 32 -o  ran2.o ran2.f90
ifort -c -O0 -g -real-size 32 -o  powell.o powell.f90
ifort -c -O0 -g -real-size 32 -o  polcof.o polcof.f90
ifort -c -O0 -g -real-size 32 -o  mnewt.o mnewt.f90
ifort -c -O0 -g -real-size 32 -o  miser.o miser.f90
ifort -c -O0 -g -real-size 32 -o  midexp.o midexp.f90
ifort -c -O0 -g -real-size 32 -o  hufdec.o hufdec.f90
ifort -c -O0 -g -real-size 32 -o  gauleg.o gauleg.f90
ifort -c -O0 -g -real-size 32 -o  gauher.o gauher.f90
ifort -c -O0 -g -real-size 32 -o  fixrts.o fixrts.f90
ifort -c -O0 -g -real-size 32 -o  expint.o expint.f90
ifort -c -O0 -g -real-size 32 -o  daub4.o daub4.f90
ifort -c -O0 -g -real-size 32 -o  convlv.o convlv.f90
ifort -c -O0 -g -real-size 32 -o  bessj0.o bessj0.f90
ifort -c -O0 -g -real-size 32 -o  balanc.o balanc.f90
ifort -c -O0 -g -real-size 32 -o  svdvar.o svdvar.f90
ifort -c -O0 -g -real-size 32 -o  svdcmp.o svdcmp.f90
ifort -c -O0 -g -real-size 32 -o  rk4.o rk4.f90
ifort -c -O0 -g -real-size 32 -o  quadct.o quadct.f90
ifort -c -O0 -g -real-size 32 -o  psdes.o psdes.f90
ifort -c -O0 -g -real-size 32 -o  mp2dfr.o mp2dfr.f90
ifort -c -O0 -g -real-size 32 -o  lnsrch.o lnsrch.f90
ifort -c -O0 -g -real-size 32 -o  ks2d1s.o ks2d1s.f90
ifort -c -O0 -g -real-size 32 -o  gammp.o gammp.f90
ifort -c -O0 -g -real-size 32 -o  elle.o elle.f90
ifort -c -O0 -g -real-size 32 -o  dawson.o dawson.f90
ifort -c -O0 -g -real-size 32 -o  choldc.o choldc.f90
ifort -c -O0 -g -real-size 32 -o  betacf.o betacf.f90
ifort -c -O0 -g -real-size 32 -o  bessj1.o bessj1.f90
ifort -c -O0 -g -real-size 32 -o  anneal.o anneal.f90
ifort -c -O0 -g -real-size 32 -o  zriddr.o zriddr.f90
ifort -c -O0 -g -real-size 32 -o  rzextr.o rzextr.f90
ifort -c -O0 -g -real-size 32 -o  rtsec.o rtsec.f90
ifort -c -O0 -g -real-size 32 -o  ratlsq.o ratlsq.f90
ifort -c -O0 -g -real-size 32 -o  plgndr.o plgndr.f90
ifort -c -O0 -g -real-size 32 -o  orthog.o orthog.f90
ifort -c -O0 -g -real-size 32 -o  locate.o locate.f90
ifort -c -O0 -g -real-size 32 -o  lfit.o lfit.f90
ifort -c -O0 -g -real-size 32 -o  fredex.o fredex.f90
ifort -c -O0 -g -real-size 32 -o  fourcol.o fourcol.f90
ifort -c -O0 -g -real-size 32 -o  eclazz.o eclazz.f90
ifort -c -O0 -g -real-size 32 -o  bnldev.o bnldev.f90
ifort -c -O0 -g -real-size 32 -o  bico.o bico.f90
ifort -c -O0 -g -real-size 32 -o  bessy.o bessy.f90
ifort -c -O0 -g -real-size 32 -o  bessik.o bessik.f90
ifort -c -O0 -g -real-size 32 -o  svdfit.o svdfit.f90
ifort -c -O0 -g -real-size 32 -o  sort_pic.o sort_pic.f90
ifort -c -O0 -g -real-size 32 -o  solvde.o solvde.f90
ifort -c -O0 -g -real-size 32 -o  savgol.o savgol.f90
ifort -c -O0 -g -real-size 32 -o  rsolv.o rsolv.f90
ifort -c -O0 -g -real-size 32 -o  qrdcmp.o qrdcmp.f90
ifort -c -O0 -g -real-size 32 -o  mpdiv.o mpdiv.f90
ifort -c -O0 -g -real-size 32 -o  kendl1.o kendl1.f90
ifort -c -O0 -g -real-size 32 -o  igray.o igray.f90
ifort -c -O0 -g -real-size 32 -o  hypser.o hypser.f90
ifort -c -O0 -g -real-size 32 -o  golden.o golden.f90
ifort -c -O0 -g -real-size 32 -o  four1.o four1.f90
ifort -c -O0 -g -real-size 32 -o  dfpmin.o dfpmin.f90
ifort -c -O0 -g -real-size 32 -o  chint.o chint.f90
ifort -c -O0 -g -real-size 32 -o  chebpc.o chebpc.f90
ifort -c -O0 -g -real-size 32 -o  atimes.o atimes.f90
ifort -c -O0 -g -real-size 32 -o  zbrac.o zbrac.f90
ifort -c -O0 -g -real-size 32 -o  sprstx.o sprstx.f90
ifort -c -O0 -g -real-size 32 -o  sort2.o sort2.f90
ifort -c -O0 -g -real-size 32 -o  snrm.o snrm.f90
ifort -c -O0 -g -real-size 32 -o  recur2.o recur2.f90
ifort -c -O0 -g -real-size 32 -o  quadmx.o quadmx.f90
ifort -c -O0 -g -real-size 32 -o  poidev.o poidev.f90
ifort -c -O0 -g -real-size 32 -o  pccheb.o pccheb.f90
ifort -c -O0 -g -real-size 32 -o  lop.o lop.f90
ifort -c -O0 -g -real-size 32 -o  irbit2.o irbit2.f90
ifort -c -O0 -g -real-size 32 -o  frenel.o frenel.f90
ifort -c -O0 -g -real-size 32 -o  four2_al.o four2_al.f90
ifort -c -O0 -g -real-size 32 -o  four1_al.o four1_al.f90
ifort -c -O0 -g -real-size 32 -o  decchk.o decchk.f90
ifort -c -O0 -g -real-size 32 -o  bessy1.o bessy1.f90
ifort -c -O0 -g -real-size 32 -o  bessk0.o bessk0.f90
ifort -c -O0 -g -real-size 32 -o  bcuint.o bcuint.f90
ifort -c -O0 -g -real-size 32 -o  zroots.o zroots.f90
ifort -c -O0 -g -real-size 32 -o  vegas.o vegas.f90
ifort -c -O0 -g -real-size 32 -o  twofft.o twofft.f90
ifort -c -O0 -g -real-size 32 -o  tutest.o tutest.f90
ifort -c -O0 -g -real-size 32 -o  sort_byp.o sort_byp.f90
ifort -c -O0 -g -real-size 32 -o  realft.o realft.f90
ifort -c -O0 -g -real-size 32 -o  ratval.o ratval.f90
ifort -c -O0 -g -real-size 32 -o  rank.o rank.f90
ifort -c -O0 -g -real-size 32 -o  qsimp.o qsimp.f90
ifort -c -O0 -g -real-size 32 -o  qromb.o qromb.f90
ifort -c -O0 -g -real-size 32 -o  polint.o polint.f90
ifort -c -O0 -g -real-size 32 -o  jacobn.o jacobn.f90
ifort -c -O0 -g -real-size 32 -o  irbit1.o irbit1.f90
ifort -c -O0 -g -real-size 32 -o  fourrow_.o fourrow_.f90
ifort -c -O0 -g -real-size 32 -o  four3_al.o four3_al.f90
ifort -c -O0 -g -real-size 32 -o  erfcc.o erfcc.f90
ifort -c -O0 -g -real-size 32 -o  eclass.o eclass.f90
ifort -c -O0 -g -real-size 32 -o  difeq.o difeq.f90
ifort -c -O0 -g -real-size 32 -o  bsstep.o bsstep.f90
ifort -c -O0 -g -real-size 32 -o  brent.o brent.f90
ifort -c -O0 -g -real-size 32 -o  avevar.o avevar.f90
ifort -c -O0 -g -real-size 32 -o  sort_byr.o sort_byr.f90
ifort -c -O0 -g -real-size 32 -o  slvsm2.o slvsm2.f90
ifort -c -O0 -g -real-size 32 -o  rkqs.o rkqs.f90
ifort -c -O0 -g -real-size 32 -o  rc.o rc.f90
ifort -c -O0 -g -real-size 32 -o  qtrap.o qtrap.f90
ifort -c -O0 -g -real-size 32 -o  pwt.o pwt.f90
ifort -c -O0 -g -real-size 32 -o  pade.o pade.f90
ifort -c -O0 -g -real-size 32 -o  mpmul.o mpmul.f90
ifort -c -O0 -g -real-size 32 -o  kendl2.o kendl2.f90
ifort -c -O0 -g -real-size 32 -o  jacobi.o jacobi.f90
ifort -c -O0 -g -real-size 32 -o  hufenc.o hufenc.f90
ifort -c -O0 -g -real-size 32 -o  four3.o four3.f90
ifort -c -O0 -g -real-size 32 -o  factrl.o factrl.f90
ifort -c -O0 -g -real-size 32 -o  erf.o erf.f90
ifort -c -O0 -g -real-size 32 -o  ellpi.o ellpi.f90
ifort -c -O0 -g -real-size 32 -o  covsrt.o covsrt.f90
ifort -c -O0 -g -real-size 32 -o  cholsl.o cholsl.f90
ifort -c -O0 -g -real-size 32 -o  badluk.o badluk.f90
ifort -c -O0 -g -real-size 32 -o  zrhqr.o zrhqr.f90
ifort -c -O0 -g -real-size 32 -o  sort_hea.o sort_hea.f90
ifort -c -O0 -g -real-size 32 -o  sncndn.o sncndn.f90
ifort -c -O0 -g -real-size 32 -o  sinft.o sinft.f90
ifort -c -O0 -g -real-size 32 -o  qrsolv.o qrsolv.f90
ifort -c -O0 -g -real-size 32 -o  qroot.o qroot.f90
ifort -c -O0 -g -real-size 32 -o  predic.o predic.f90
ifort -c -O0 -g -real-size 32 -o  mrqmin.o mrqmin.f90
ifort -c -O0 -g -real-size 32 -o  mprove.o mprove.f90
ifort -c -O0 -g -real-size 32 -o  mnbrak.o mnbrak.f90
ifort -c -O0 -g -real-size 32 -o  mglin.o mglin.f90
ifort -c -O0 -g -real-size 32 -o  icrc.o icrc.f90
ifort -c -O0 -g -real-size 32 -o  gcf.o gcf.f90
ifort -c -O0 -g -real-size 32 -o  fred2.o fred2.f90
ifort -c -O0 -g -real-size 32 -o  ei.o ei.f90
ifort -c -O0 -g -real-size 32 -o  dfridr.o dfridr.f90
ifort -c -O0 -g -real-size 32 -o  ddpoly.o ddpoly.f90
ifort -c -O0 -g -real-size 32 -o  cisi.o cisi.f90
ifort -c -O0 -g -real-size 32 -o  chebft.o chebft.f90
ifort -c -O0 -g -real-size 32 -o  bcucof.o bcucof.f90


# Criar a biblioteca estática a partir dos arquivos objeto .o
ar rcs /src/libnr.a *.o

echo "Compilação concluída. A biblioteca estática libnr.a foi criada."